# Generated by Django 5.2.4 on 2025-07-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(max_length=50)),
                ('product_brand', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='User/')),
            ],
        ),
    ]
