# Generated by Django 5.2.4 on 2025-07-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product_id',
        ),
        migrations.AddField(
            model_name='user',
            name='product_name',
            field=models.CharField(default='Product A', max_length=100),
        ),
    ]
