# Generated by Django 5.2.4 on 2025-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_product_id_user_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
